# Docker Compose for Open Ticket v4
services:
  openticket:
    build: .
    volumes:
      - config:/home/container/config
      - database:/home/container/database
      - plugins:/home/container/plugins
    restart: unless-stopped
    container_name: open-ticket

volumes:
  config:
  database:
  plugins: