///////////////////////////////////////
//OPEN TICKET LANGUAGE MAPPINGS
///////////////////////////////////////
import * as api from "@open-discord-bots/framework/api"

/**## ODLanguageManagerIdMappings `interface`
 * A list of all available IDs in the default `ODLanguageManager` class in `opendiscord`.
 * It's used to generate typescript declarations for this class.
 */
export interface ODLanguageManagerIdMappings extends api.ODLanguageManagerIdConstraint {
    "opendiscord:custom":api.ODLanguage,
    "opendiscord:english":api.ODLanguage,
    "opendiscord:dutch":api.ODLanguage,
    "opendiscord:portuguese":api.ODLanguage,
    "opendiscord:czech":api.ODLanguage,
    "opendiscord:german":api.ODLanguage,
    "opendiscord:catalan":api.ODLanguage,
    "opendiscord:hungarian":api.ODLanguage,
    "opendiscord:spanish":api.ODLanguage,
    "opendiscord:romanian":api.ODLanguage,
    "opendiscord:ukrainian":api.ODLanguage,
    "opendiscord:indonesian":api.ODLanguage,
    "opendiscord:italian":api.ODLanguage,
    "opendiscord:estonian":api.ODLanguage,
    "opendiscord:finnish":api.ODLanguage,
    "opendiscord:danish":api.ODLanguage,
    "opendiscord:thai":api.ODLanguage,
    "opendiscord:turkish":api.ODLanguage,
    "opendiscord:french":api.ODLanguage,
    "opendiscord:arabic":api.ODLanguage,
    "opendiscord:hindi":api.ODLanguage,
    "opendiscord:lithuanian":api.ODLanguage,
    "opendiscord:polish":api.ODLanguage,
    "opendiscord:latvian":api.ODLanguage,
    "opendiscord:norwegian":api.ODLanguage,
    "opendiscord:russian":api.ODLanguage,
    "opendiscord:swedish":api.ODLanguage,
    "opendiscord:vietnamese":api.ODLanguage,
    "opendiscord:persian":api.ODLanguage,
    "opendiscord:bengali":api.ODLanguage,
    "opendiscord:greek":api.ODLanguage,
    "opendiscord:japanese":api.ODLanguage,
    "opendiscord:korean":api.ODLanguage,
    "opendiscord:kurdish":api.ODLanguage,
    "opendiscord:simplified-chinese":api.ODLanguage,
    "opendiscord:traditional-chinese":api.ODLanguage,
    "opendiscord:slovenian":api.ODLanguage,
    "opendiscord:tamil":api.ODLanguage,
    "opendiscord:khmer  ":api.ODLanguage,
    //ADD NEW LANGUAGES HERE!!!
}

/**## ODLanguageManagerTranslationIdMappings `type`
 * A list of all available translation IDs in the default `ODLanguageManager` class in `opendiscord`.
 * It's used to generate typescript declarations for this class.
 */
export type ODLanguageManagerTranslationIdMappings = (
    "checker.system.headerOpenTicket"|
    "checker.system.typeError"|
    "checker.system.typeWarning"|
    "checker.system.typeInfo"|
    "checker.system.headerConfigChecker"|
    "checker.system.headerDescription"|
    "checker.system.footerError"|
    "checker.system.footerWarning"|
    "checker.system.footerSupport"|
    "checker.system.compactInformation"|
    "checker.system.dataPath"|
    "checker.system.dataDocs"|
    "checker.system.dataMessages"|

    "checker.messages.invalidType"|
    "checker.messages.propertyMissing"|
    "checker.messages.propertyOptional"|
    "checker.messages.objectDisabled"|
    "checker.messages.nullInvalid"|
    "checker.messages.switchInvalidType"|
    "checker.messages.objectSwitchInvalid"|

    "checker.messages.stringTooShort"|
    "checker.messages.stringTooLong"|
    "checker.messages.stringLengthInvalid"|
    "checker.messages.stringStartsWith"|
    "checker.messages.stringEndsWith"|
    "checker.messages.stringContains"|
    "checker.messages.stringChoices"|
    "checker.messages.stringRegex"|
    "checker.messages.stringInvertedContains"|
    "checker.messages.stringLowercase"|
    "checker.messages.stringUppercase"|
    "checker.messages.stringSpecialCharacters"|
    "checker.messages.stringNoSpaces"|
    "checker.messages.stringCapitalWord"|
    "checker.messages.stringCapitalSentence"|
    "checker.messages.stringPunctuation"|

    "checker.messages.numberTooShort"|
    "checker.messages.numberTooLong"|
    "checker.messages.numberLengthInvalid"|
    "checker.messages.numberTooSmall"|
    "checker.messages.numberTooLarge"|
    "checker.messages.numberNotEqual"|
    "checker.messages.numberStep"|
    "checker.messages.numberStepOffset"|
    "checker.messages.numberStartsWith"|
    "checker.messages.numberEndsWith"|
    "checker.messages.numberContains"|
    "checker.messages.numberChoices"|
    "checker.messages.numberFloat"|
    "checker.messages.numberNegative"|
    "checker.messages.numberPositive"|
    "checker.messages.numberZero"|
    "checker.messages.numberNan"|
    "checker.messages.numberInvertedContains"|

    "checker.messages.booleanTrue"|
    "checker.messages.booleanFalse"|

    "checker.messages.arrayEmptyDisabled"|
    "checker.messages.arrayEmptyRequired"|
    "checker.messages.arrayTooShort"|
    "checker.messages.arrayTooLong"|
    "checker.messages.arrayLengthInvalid"|
    "checker.messages.arrayInvalidTypes"|
    "checker.messages.arrayDouble"|

    "checker.messages.discordInvalidId"|
    "checker.messages.discordInvalidIdOptions"|
    "checker.messages.discordInvalidToken"|
    "checker.messages.colorInvalid"|
    "checker.messages.emojiTooShort"|
    "checker.messages.emojiTooLong"|
    "checker.messages.emojiCustom"|
    "checker.messages.emojiInvalid"|
    "checker.messages.urlInvalid"|
    "checker.messages.urlInvalidHttp"|
    "checker.messages.urlInvalidProtocol"|
    "checker.messages.urlInvalidHostname"|
    "checker.messages.urlInvalidExtension"|
    "checker.messages.urlInvalidPath"|
    "checker.messages.idNotUnique"|
    "checker.messages.idNonExistent"|
    "checker.messages.invalidLanguage"|
    "checker.messages.invalidButton"|
    "checker.messages.unusedOption"|
    "checker.messages.unusedQuestion"|
    "checker.messages.dropdownOption"|
    "checker.messages.customInvalidVersion"|

    "actions.buttons.create"|
    "actions.buttons.close"|
    "actions.buttons.delete"|
    "actions.buttons.reopen"|
    "actions.buttons.claim"|
    "actions.buttons.unclaim"|
    "actions.buttons.pin"|
    "actions.buttons.unpin"|
    "actions.buttons.clear"|
    "actions.buttons.helpSwitchSlash"|
    "actions.buttons.helpSwitchText"|
    "actions.buttons.helpPage"|
    "actions.buttons.withReason"|
    "actions.buttons.withoutTranscript"|
    "actions.buttons.blacklistAdd"|
    "actions.buttons.blacklistRemove"|

    "actions.titles.created"|
    "actions.titles.close"|
    "actions.titles.delete"|
    "actions.titles.reopen"|
    "actions.titles.claim"|
    "actions.titles.unclaim"|
    "actions.titles.pin"|
    "actions.titles.unpin"|
    "actions.titles.rename"|
    "actions.titles.move"|
    "actions.titles.add"|
    "actions.titles.remove"|

    "actions.titles.help"|
    "actions.titles.statsReset"|
    "actions.titles.blacklistAdd"|
    "actions.titles.blacklistRemove"|
    "actions.titles.blacklistGet"|
    "actions.titles.blacklistView"|
    "actions.titles.blacklistAddDm"|
    "actions.titles.blacklistRemoveDm"|
    "actions.titles.clear"|
    "actions.titles.clearTickets"|
    "actions.titles.roles"|

    "actions.titles.autoclose"|
    "actions.titles.autocloseEnabled"|
    "actions.titles.autocloseDisabled"|
    "actions.titles.autodelete"|
    "actions.titles.autodeleteEnabled"|
    "actions.titles.autodeleteDisabled"|

    "actions.titles.topicSet"|
    "actions.titles.prioritySet"|
    "actions.titles.priorityGet"|
    "actions.titles.transfer"|
    "actions.titles.transcripts"|

    "actions.descriptions.create"|
    "actions.descriptions.close"|
    "actions.descriptions.delete"|
    "actions.descriptions.reopen"|
    "actions.descriptions.claim"|
    "actions.descriptions.unclaim"|
    "actions.descriptions.pin"|
    "actions.descriptions.unpin"|
    "actions.descriptions.rename"|
    "actions.descriptions.move"|
    "actions.descriptions.add"|
    "actions.descriptions.remove"|

    "actions.descriptions.helpExplanation"|
    "actions.descriptions.statsReset"|
    "actions.descriptions.statsError"|
    "actions.descriptions.blacklistAdd"|
    "actions.descriptions.blacklistRemove"|
    "actions.descriptions.blacklistGetSuccess"|
    "actions.descriptions.blacklistGetEmpty"|
    "actions.descriptions.blacklistViewEmpty"|
    "actions.descriptions.blacklistViewTip"|
    "actions.descriptions.clearVerify"|
    "actions.descriptions.clearReady"|
    "actions.descriptions.rolesEmpty"|

    "actions.descriptions.autocloseLeave"|
    "actions.descriptions.autocloseTimeout"|
    "actions.descriptions.autodeleteLeave"|
    "actions.descriptions.autodeleteTimeout"|
    "actions.descriptions.autocloseEnabled"|
    "actions.descriptions.autocloseDisabled"|
    "actions.descriptions.autodeleteEnabled"|
    "actions.descriptions.autodeleteDisabled"|

    "actions.descriptions.ticketMessageLimit"|
    "actions.descriptions.ticketMessageAutoclose"|
    "actions.descriptions.ticketMessageAutodelete"|
    "actions.descriptions.panelReady"|

    "actions.descriptions.topicSet"|
    "actions.descriptions.prioritySet"|
    "actions.descriptions.priorityGet"|
    "actions.descriptions.transfer"|

    "actions.modal.closePlaceholder"|
    "actions.modal.deletePlaceholder"|
    "actions.modal.reopenPlaceholder"|
    "actions.modal.claimPlaceholder"|
    "actions.modal.unclaimPlaceholder"|
    "actions.modal.pinPlaceholder"|
    "actions.modal.unpinPlaceholder"|

    "actions.logs.createLog"|
    "actions.logs.closeLog"|
    "actions.logs.closeDm"|
    "actions.logs.deleteLog"|
    "actions.logs.deleteDm"|
    "actions.logs.reopenLog"|
    "actions.logs.reopenDm"|
    "actions.logs.claimLog"|
    "actions.logs.claimDm"|
    "actions.logs.unclaimLog"|
    "actions.logs.unclaimDm"|
    "actions.logs.pinLog"|
    "actions.logs.pinDm"|
    "actions.logs.unpinLog"|
    "actions.logs.unpinDm"|
    "actions.logs.renameLog"|
    "actions.logs.renameDm"|
    "actions.logs.moveLog"|
    "actions.logs.moveDm"|
    "actions.logs.addLog"|
    "actions.logs.addDm"|
    "actions.logs.removeLog"|
    "actions.logs.removeDm"|

    "actions.logs.blacklistAddLog"|
    "actions.logs.blacklistRemoveLog"|
    "actions.logs.blacklistAddDm"|
    "actions.logs.blacklistRemoveDm"|
    "actions.logs.clearLog"|

    "actions.logs.transferLog"|
    "actions.logs.transferDm"|
    "actions.logs.prioritySetLog"|
    "actions.logs.prioritySetDm"|
    "actions.logs.roleUpdateLog"|
    "actions.logs.roleUpdateDm"|
    "actions.logs.topicSetLog"|
    "actions.logs.topicSetDm"|
    
    "transcripts.success.visit"|
    "transcripts.success.ready"|
    "transcripts.success.textFileDescription"|
    "transcripts.success.htmlProgress"|

    "transcripts.success.createdChannel"|
    "transcripts.success.createdCreator"|
    "transcripts.success.createdParticipant"|
    "transcripts.success.createdActiveAdmin"|
    "transcripts.success.createdEveryAdmin"|
    "transcripts.success.createdOther"|

    "transcripts.errors.retry"|
    "transcripts.errors.continue"|
    "transcripts.errors.backup"|
    "transcripts.errors.error"|
    "transcripts.errors.title"|
    "transcripts.errors.noHistory"|
    "transcripts.errors.historyNotSupported"|
    
    "transcripts.text.messagesTitle"|
    "transcripts.text.embedTitle"|
    "transcripts.text.fileTitle"|
    "transcripts.text.fieldsTitle"|
    "transcripts.text.reactionsTitle"|
    "transcripts.text.statsTitle"|
    "transcripts.text.emptyContent"|
    "transcripts.text.noTitle"|
    "transcripts.text.noDesc"|

    "errors.titles.internalError"|
    "errors.titles.optionMissing"|
    "errors.titles.optionInvalid"|
    "errors.titles.unknownCommand"|
    "errors.titles.noPermissions"|
    "errors.titles.unknownTicket"|
    "errors.titles.deprecatedTicket"|
    "errors.titles.unknownOption"|
    "errors.titles.unknownPanel"|
    "errors.titles.notInGuild"|
    "errors.titles.channelRename"|
    "errors.titles.channelCategory"|
    "errors.titles.busy"|
    "errors.titles.permissionError"|

    "errors.descriptions.askForInfo"|
    "errors.descriptions.askForInfoResolve"|
    "errors.descriptions.internalError"|
    "errors.descriptions.optionMissing"|
    "errors.descriptions.optionInvalid"|
    "errors.descriptions.optionInvalidChoose"|
    "errors.descriptions.unknownCommand"|
    "errors.descriptions.noPermissions"|
    "errors.descriptions.noPermissionsList"|
    "errors.descriptions.noPermissionsCooldown"|
    "errors.descriptions.noPermissionsBlacklist"|
    "errors.descriptions.noPermissionsLimitGlobal"|
    "errors.descriptions.noPermissionsLimitGlobalUser"|
    "errors.descriptions.noPermissionsLimitOption"|
    "errors.descriptions.noPermissionsLimitOptionUser"|
    "errors.descriptions.unknownTicket"|
    "errors.descriptions.deprecatedTicket"|
    "errors.descriptions.notInGuild"|
    "errors.descriptions.channelRename"|
    "errors.descriptions.channelCategory"|
    "errors.descriptions.channelRenameSource"|
    "errors.descriptions.busy"|
    "errors.descriptions.closeBeforeMessage"|
    "errors.descriptions.closeBeforeAdminMessage"|
    "errors.descriptions.unableToCreateTicket"|
    "errors.descriptions.messageMissing"|
    "errors.descriptions.stateExpired"|
    "errors.descriptions.panelStateExpired"|
    
    "errors.optionInvalidReasons.stringRegex"|
    "errors.optionInvalidReasons.stringMinLength"|
    "errors.optionInvalidReasons.stringMaxLength"|
    "errors.optionInvalidReasons.numberInvalid"|
    "errors.optionInvalidReasons.numberMin"|
    "errors.optionInvalidReasons.numberMax"|
    "errors.optionInvalidReasons.numberDecimal"|
    "errors.optionInvalidReasons.numberNegative"|
    "errors.optionInvalidReasons.numberPositive"|
    "errors.optionInvalidReasons.numberZero"|
    "errors.optionInvalidReasons.channelNotFound"|
    "errors.optionInvalidReasons.userNotFound"|
    "errors.optionInvalidReasons.roleNotFound"|
    "errors.optionInvalidReasons.memberNotFound"|
    "errors.optionInvalidReasons.mentionableNotFound"|
    "errors.optionInvalidReasons.channelType"|
    "errors.optionInvalidReasons.notInGuild"|

    "errors.permissions.developer"|
    "errors.permissions.owner"|
    "errors.permissions.admin"|
    "errors.permissions.moderator"|
    "errors.permissions.support"|
    "errors.permissions.member"|
    "errors.permissions.discord-administrator"|

    "errors.actionInvalid.close"|
    "errors.actionInvalid.reopen"|
    "errors.actionInvalid.claim"|
    "errors.actionInvalid.unclaim"|
    "errors.actionInvalid.pin"|
    "errors.actionInvalid.unpin"|
    "errors.actionInvalid.add"|
    "errors.actionInvalid.remove"|

    "params.uppercase.ticket"|
    "params.uppercase.tickets"|
    "params.uppercase.reason"|
    "params.uppercase.creator"|
    "params.uppercase.remaining"|
    "params.uppercase.added"|
    "params.uppercase.removed"|
    "params.uppercase.filter"|
    "params.uppercase.method"|
    "params.uppercase.type"|
    "params.uppercase.blacklisted"|
    "params.uppercase.panel"|
    "params.uppercase.command"|
    "params.uppercase.system"|
    "params.uppercase.true"|
    "params.uppercase.false"|
    "params.uppercase.syntax"|
    "params.uppercase.originalName"|
    "params.uppercase.newName"|
    "params.uppercase.originalCategory"|
    "params.uppercase.newCategory"|
    "params.uppercase.until"|
    "params.uppercase.validOptions"|
    "params.uppercase.validPanels"|
    "params.uppercase.autoclose"|
    "params.uppercase.autodelete"|
    "params.uppercase.startupDate"|
    "params.uppercase.version"|
    "params.uppercase.name"|
    "params.uppercase.role"|
    "params.uppercase.status"|
    "params.uppercase.claimed"|
    "params.uppercase.pinned"|
    "params.uppercase.creationDate"|

    "params.uppercase.noone"|
    "params.uppercase.open"|
    "params.uppercase.closed"|
    "params.uppercase.priority"|
    "params.uppercase.status"|
    "params.uppercase.participants"|
    "params.uppercase.yes"|
    "params.uppercase.no"|
    "params.uppercase.accept"|
    "params.uppercase.cancel"|
    "params.uppercase.option"|
    "params.uppercase.topic"|
    "params.uppercase.uptime"|
    "params.uppercase.messages"|
    "params.uppercase.embeds"|
    "params.uppercase.files"|
    "params.uppercase.components"|
    "params.uppercase.cooldown"|
    "params.uppercase.maxTickets"|
    "params.uppercase.admins"|
    "params.uppercase.roles"|
    "params.uppercase.size"|

    "params.lowercase.text"|
    "params.lowercase.html"|
    "params.lowercase.command"|
    "params.lowercase.modal"|
    "params.lowercase.button"|
    "params.lowercase.dropdown"|
    "params.lowercase.method"|

    "commands.reason"|
    "commands.help"|
    "commands.panel"|
    "commands.panelId"|
    "commands.panelAutoUpdate"|
    "commands.ticket"|
    "commands.ticketId"|
    "commands.ticketOtherUser"|
    "commands.close"|
    "commands.delete"|
    "commands.deleteNoTranscript"|
    "commands.reopen"|
    "commands.claim"|
    "commands.claimUser"|
    "commands.unclaim"|
    "commands.pin"|
    "commands.unpin"|
    "commands.move"|
    "commands.moveId"|
    "commands.rename"|
    "commands.renameName"|
    "commands.add"|
    "commands.addUser"|
    "commands.remove"|
    "commands.removeUser"|
    "commands.blacklist"|
    "commands.blacklistView"|
    "commands.blacklistAdd"|
    "commands.blacklistRemove"|
    "commands.blacklistGet"|
    "commands.blacklistGetUser"|
    "commands.stats"|
    "commands.statsReset"|
    "commands.statsGlobal"|
    "commands.statsUser"|
    "commands.statsUserUser"|
    "commands.statsTicket"|
    "commands.statsTicketTicket"|
    "commands.clear"|
    "commands.clearFilter"|

    "commands.clearFilters.all"|
    "commands.clearFilters.open"|
    "commands.clearFilters.close"|
    "commands.clearFilters.claim"|
    "commands.clearFilters.unclaim"|
    "commands.clearFilters.pin"|
    "commands.clearFilters.unpin"|
    "commands.clearFilters.autoclose"|

    "commands.autoclose"|
    "commands.autocloseDisable"|
    "commands.autocloseEnable"|
    "commands.autocloseEnableTime"|
    "commands.autodelete"|
    "commands.autodeleteDisable"|
    "commands.autodeleteEnable"|
    "commands.autodeleteEnableTime"|

    "commands.topic"|
    "commands.topicSet"|
    "commands.topicValue"|
    "commands.topicList"|
    "commands.priority"|
    "commands.prioritySet"|
    "commands.priorityValue"|
    "commands.priorityGet"|
    "commands.priorityList"|
    "commands.transfer"|
    "commands.transferUser"|
    "commands.transcripts"|
    "commands.transcriptsUser"|

    "helpMenu.help"|
    "helpMenu.ticket"|
    "helpMenu.close"|
    "helpMenu.delete"|
    "helpMenu.reopen"|
    "helpMenu.pin"|
    "helpMenu.unpin"|
    "helpMenu.move"|
    "helpMenu.rename"|
    "helpMenu.claim"|
    "helpMenu.unclaim"|
    "helpMenu.add"|
    "helpMenu.remove"|
    "helpMenu.panel"|
    "helpMenu.blacklistView"|
    "helpMenu.blacklistAdd"|
    "helpMenu.blacklistRemove"|
    "helpMenu.blacklistGet"|
    "helpMenu.statsGlobal"|
    "helpMenu.statsTicket"|
    "helpMenu.statsUser"|
    "helpMenu.statsReset"|
    "helpMenu.autocloseDisable"|
    "helpMenu.autocloseEnable"|
    "helpMenu.autodeleteDisable"|
    "helpMenu.autodeleteEnable"|

    "helpMenu.categories.general"|
    "helpMenu.categories.basicTicket"|
    "helpMenu.categories.advancedTicket"|
    "helpMenu.categories.userTicket"|
    "helpMenu.categories.admin"|
    "helpMenu.categories.advanced"|
    "helpMenu.categories.extra"|

    "stats.scopes.global"|
    "stats.scopes.system"|
    "stats.scopes.user"|
    "stats.scopes.ticket"|
    "stats.scopes.participants"|
    "stats.scopes.messages"|

    "stats.properties.ticketsCreated"|
    "stats.properties.ticketsClosed"|
    "stats.properties.ticketsDeleted"|
    "stats.properties.ticketsReopened"|
    "stats.properties.ticketsAutoclosed"|
    "stats.properties.ticketsClaimed"|
    "stats.properties.ticketsPinned"|
    "stats.properties.ticketsMoved"|
    "stats.properties.usersBlacklisted"|
    "stats.properties.transcriptsCreated"|
    "stats.properties.ticketsAutodeleted"|
    "stats.properties.ticketsTransferred"|
    "stats.properties.ticketVolume"|
    "stats.properties.averageTickets"|
    "stats.properties.currentTickets"|
    "stats.properties.age"|
    "stats.properties.responseTime"|
    "stats.properties.resolutionTime"|
    "stats.properties.createdOn"|
    "stats.properties.createdBy"|
    "stats.properties.closedOn"|
    "stats.properties.closedBy"|
    "stats.properties.claimedOn"|
    "stats.properties.claimedBy"|
    "stats.properties.pinnedOn"|
    "stats.properties.pinnedBy"|
    "stats.properties.deletedOn"|
    "stats.properties.deletedBy"|

    "stats.roles.developer"|
    "stats.roles.serverOwner"|
    "stats.roles.serverAdmin"|
    "stats.roles.moderator"|
    "stats.roles.support"|
    "stats.roles.member"|

    "panel.selectTicket"|
    "panel.selectRole"|
    "panel.selectOption"|
    "panel.selectPriorityLevel"|

    "priorities.urgent"|
    "priorities.veryHigh"|
    "priorities.high"|
    "priorities.normal"|
    "priorities.low"|
    "priorities.veryLow"|
    "priorities.none"
)

/////////////////////////////
////// MAPPED MANAGERS //////
/////////////////////////////

/**## ODMappedLanguageManager `class
 * A special class with types for the Open Ticket `ODLanguageManager` class.
 */
export class ODMappedLanguageManager extends api.ODLanguageManager<ODLanguageManagerIdMappings,ODLanguageManagerTranslationIdMappings> {}